name: Generate iOS Project

on:
  workflow_dispatch:

jobs:
  prebuild-ios:
    runs-on: ubuntu-latest
    env:
      EAS_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g eas-cli
      - run: eas prebuild --platform ios --skip-install
      - run: ls ios
      - uses: actions/upload-artifact@v4
        with:
          name: ios-project
          path: ios
